### ISSUE TITLE
Simulation crashes when reaching Intermediate state with peptide as ligand

### ISSUE THREAD

**Issue by r-aschwanden** [Gallicchio-Lab/AToM-OpenMM#1]
Hello, I only recently started to use your plugin. The examples ran without issue, and so did a custom complex, consisting of a protein and a small molecule. 
I then also tried a cyclic peptide as a ligand, and changed part of the setup to not parameterize the peptide with antechamber, but rather to read it like a protein (pdb, prmtop, inpcrd). Setup and all equilibrations ran without error. The simulation also starts and finishes for the first 10 replicas without issue.
When launching replica 11 and 12, the MD crashes. After restarting, reading the checkpoint files is fine but every subsequent MD simulation crashes until it finally reports that no more compute devices are alive. Attached is the console output from one of the restart attempts.

[std-out.txt](https://github.com/Gallicchio-Lab/AToM-OpenMM/files/9166412/std-out.txt)

I will gladly provide further information that would help to resolve the issue. 
Thank you, 
Roman

**Comment by egallicc** [comment]
thank you for trying AToM! 

Is this for an absolute binding free energy calculation? 

MD failures like the one you are describing are usually caused by inconsistent binding site restraint settings. Please check the structure after equilibration (`<jobname>_0.pdb`) to confirm that is satsfies the binding site definition. 

Failures near the alchemical intermediate in ABFE calculations also suggest that the transformation is too large for the alchemical schedule to handle. How large is the peptide? We usually try to avoid ABFEs for ligands with more than 15-20 heavy atoms. RBFEs are less affected by ligand size. It is often possible to get the ABFE of a large ligand using a series of RBFEs starting with a small fragment. Doing that for a cyclic peptide would require some thought ...

**Comment by r-aschwanden** [comment]
Thank you for the suggestion.

This was an absolute binding free energy calculation. In the meantime, I also tried the relative binding free energy protocol but it yields the same error message.

I think the vsite atoms do match the desired ones. I should take the numbers from the text output and add 1, since openmm assigns atom numbers starting from 0 instead of 1? Additionally, I added the lines from one of your examples to also check the displaced ligand pdb and that one seems also fine.
What I did notice however is the protein chain is not terminated. The peptide can then be considered as a continuation of the protein. I will manually insert the TER line between protein and peptide and let you know if that worked.

The peptide consists of 13 amino acids bonded by a disulfide bridge. I assume the fragmentation could be rather difficult as the binding site is quite superficial.

**Comment by egallicc** [comment]
Yes, OpenMM indexes atoms starting with 0. The tutorial workflows shift atom indexes from 1 to 0 automatically before inserting them in the setup files (`mintherm.py`, etc.) and in the replica-exchange `.cntl` file.

Relative calculations require 3 reference atoms of each ligand to define their Cartesian reference frame for alignment. One strategy could be to pick atoms in the same residue, preferably the backbone. If the peptides are rigid it could make sense to pick reference atoms in different residues. Regardless, especially if they are different and flexible, the peptides will likely end up in poor alignment in parts of their structures causing slow convergence.

We do not have a lot of experience studying peptides with AToM. Our targets have been drug-like molecules. For peptides, we have used successfully a protocol similar to AToM's but with implicit solvation  [https://www.frontiersin.org/articles/10.3389/fmolb.2018.00022/full](https://www.frontiersin.org/articles/10.3389/fmolb.2018.00022/full). OpenMM has various implicit solvent models and they should work with AToM out of the box.
