### ISSUE TITLE
Extend to amino acid mutation free energy?

### ISSUE THREAD

**Issue by kexul** [Gallicchio-Lab/AToM-OpenMM#10]
Dear AToM developers: 
Do you think this method is suitable for protein mutation free energy calculation? Which might be useful to guide antibody design. 
One of the disadvantages I can name is that the simulation box may become very big. Currently, I see that 20 angstroms is used for splitting the protein and ligand, not sure how long would be enough for proteins. Do you think there are other potential pitfalls? 
I've seen your roadmap in this [slide](https://twitter.com/GallicchioEmi/status/1563516530281037827), there seems to be no plan for protein mutation free energy at present. 🤔

**Comment by egallicc** [comment]
The Alchemical Transfer Method is suitable for chemical equilibria that can be expressed in terms of a coordinate transformation (e.g. ligand in solution vs. ligand in the receptor site for binding). It is not apparent how an aminoacid mutation could be cast in terms of a coordinate transformation. We are looking at related applications of ATM, but it is too early to tell if they are feasible/useful.

The current dual-topology implementation of ATM does not apply, I think, to large ligands, such as peptides and proteins.

**Comment by kexul** [comment]
Many thanks for your quick response! 🤗
