### ISSUE TITLE
Error in ABFE Analysis 

### ISSUE THREAD

**Issue by vemaparna** [Gallicchio-Lab/AToM-OpenMM#11]
Hi! 
 I could succesffuly complete the absolute binding free energy example of the host-guest complex(temoa-g1). But im stuck with the analysis. Im new to R and could not trace out the problem. The uwham_analysis.Rout ends up with the following error
===========
Error in if (alpha > 0) { : missing value where TRUE/FALSE needed
Calls: bias.fcn
Execution halted
============
Can you help me to solve the issue
[uwham_analysis_Rout.txt](https://github.com/Gallicchio-Lab/AToM-OpenMM/files/10103669/uwham_analysis_Rout.txt)

**Comment by egallicc** [comment]
This error could be caused by missing data. Are there replica directories (`r? r??`) and do they contain `.out` files with at least 20 samples?

**Comment by vemaparna** [comment]
replica directories are present but have only 9 samples till r10, and 8 samples from r11 to r21. But i did not receive any error message indicating incomplete simulation

**Comment by egallicc** [comment]
The
```
./analyze.sh 20
```
command mentioned in the example assumes that more than 20 samples have been collected. `20` in this case is the number of samples to discard from the beginning of the simulation. Try `./analyze.sh 0` to avoid discarding samples. But it is probably preferable to run the simulation longer to collect more samples. In most cases, just relaunch the simulation in the same folder to add more samples.

**Comment by vemaparna** [comment]
Thank you, i could relauch the simulation. But how to decide how long i should run the simulation. How do we decide and fix the wall time. I have seen that even in the RBFE example, only 1 sample was generated for a wall time of 240 minutes. The more the number of samples, DGb keeps on changing. What should be the deciding factor

**Comment by vemaparna** [comment]
Thanks for the reply. Im running the host-guest RBFE example with a single GPU (Quadro K 2000) in HP Z820 workstation with OpenCL. I will try the same in another workstation with a single GPU (Quadro P620) with CUDA
