### ISSUE TITLE
Generating `asyncre.cntl` for a new system?

### ISSUE THREAD

**Issue by JSLJ23** [Gallicchio-Lab/AToM-OpenMM#14]
Hi, I was wondering what would be necessary to generate the `asyncre.cntl` file for a new system? I understand that some parts are output by `mdlambda.py` but there are quite a number of parameters before and after that seem to be specifically configured for the system. May I know how this is done?

I am trying to reference the temoa-g1 example for a new protein ligand system.

Also, I am trying to understand what `mdlamda.py` is doing, the ATM which seems to be incrementally changing the `atmforce.Lambda1()` and `atmforce.Lambda2()` but the system only has one copy of the ligand. And at the step where the PDB file is saved, the ligand is just translated by the displacement vector. Is this just done for visualisation purposes or is there something I am missing?

**Comment by JSLJ23** [comment]
Also may I know which part of the code to run the absolute binding free energy calculations requires the nodefile? I am running it on a machine with one GPU so is this still necessary?

**Comment by egallicc** [comment]
I recommend the posted workflows as a starting point to assemble `asyncre.cntl ` files for your purposes. For ABFE calculations look at the [FKBP](https://github.com/Gallicchio-Lab/AToM-OpenMM/tree/master/examples/ABFE/fkbp) workflow, for RBFE calculations look at the [CDK2](https://github.com/Gallicchio-Lab/AToM-OpenMM/tree/master/examples/RBFE/cdk2) workflow.

Try to follow the inline comments to learn the meaning of each setting. Some of the settings are related to theoretical advances discussed in our publications. It might be necessary to look at them to gain a full understanding of some of these aspects. We plan to publish a full set of documentation at some point. But for now, this is all we have.

**Comment by egallicc** [comment]
The nodefile is required for production; the replica exchange molecular dynamics step. A nodefile is required whether you use GPUs. CPUs, or a mix of them.

**Comment by JSLJ23** [comment]
Ok thanks for the clarification regarding the `asyncre.cntl` file parameters, I will look into the FKBP example next. I was trying to understand the temoa-g1 because it seemed more straightforward. Noted on the nodefile requirements as well.

I've run the temoa-g1 example for 24 hours and while trying to run the downstream analysis code, something in the uwham_analysis.R script is breaking but I can't seem to figure out what is it.

The last output of the .Rout file shows:
> #runs UWHAM
out <- uwham.r(label=statelabels, logQ=neg.pot,ufactormax=1,ufactormin=1)
Error in uwham(label = label[mask], logQ = neg.pot[mask, ], init = iniz) : 
  inconsistent sum(size) and dim(logQ)[1]
Calls: uwham.r -> uwham
Execution halted

**Comment by JSLJ23** [comment]
Looking into the uwham_analysis.R, it seems the `neg.pot` matrix has a bunch of NaNs and Infs, is this due to some error in the calculation on my part?
![image](https://user-images.githubusercontent.com/53618125/212594706-8d5d11d9-6008-42ef-8eaf-ad48536458d1.png)

Here is my `repl.cycle.state.temp.lambda1.lambda2.alpha.u0.w0.epot.epert.dat` zipped.
[repl.cycle.state.temp.lambda1.lambda2.alpha.u0.w0.epot.epert.zip](https://github.com/Gallicchio-Lab/AToM-OpenMM/files/10422362/repl.cycle.state.temp.lambda1.lambda2.alpha.u0.w0.epot.epert.zip)

**Comment by egallicc** [comment]
I suspect you are using an outdated script. We no longer use that intermediate data file. Can you please explain in detail the process you are following? Also, it would be great if you could create a separate issue for this UWHAM failure. I am closing this one in regard to the .cntl file.

**Comment by JSLJ23** [comment]
You're right, my bad. I copied the wrong analysis script from the other scripts folder.
I copied the one from the /ABFE/scripts and running `./analyze.sh 20` gave :

>DGb = -4.549384 +- 0.132016 range 20 617

Thank you.

**Comment by egallicc** [comment]
Could you please let us know the location of the old script? So that it does not cause further confusion.

**Comment by JSLJ23** [comment]
It is from /examples/scripts. I accidentially copied the `analyze.sh` and `uwham_analysis.R` from there instead of the ones in /examples/ABFE/scripts.
