### ISSUE TITLE
Questions on wall time vs production steps?

### ISSUE THREAD

**Issue by nathanmlim** [Gallicchio-Lab/AToM-OpenMM#22]
I know in OpenMM you can advance the simulation by `runForClockTime` or `step`. In the asyncre_template files, I see the option for both `WALL_TIME` and `PRODUCTION_STEPS`. Does one setting take precedence over the other? 

In the CDK2 example, the settings are

- WALL_TIME = 480 (mins)
- PRODUCTION_STEPS = '20000'
- TIME_STEP = 0.002 (picoseconds)

Based on the README in the cdk2 example, which says the simulation will run for 8 hours. Am I correct to assume that WALL_TIME takes precedence over the PRODUCTION_STEPS? If I wanted to run for a set simulation time instead, say 5ns. Should I simply remove the WALL_TIME parameter and change the PRODUCTION_STEPS accordingly?

Separately, is there a way to add reporting the speed of the simulation to the log file?

**Comment by egallicc** [comment]
WALL_TIME is the maximum wall-clock time in minutes that the simulation will run for.

PRODUCTION_STEPS is the number of MD steps each replica will run for before checkpointing and exchanging with other replicas.

TIME_STEP is the MD time-step in ps

There is a parameter (MAX_SAMPLES) that I don't think we mention in the tutorials that stops the simulation if the given number of perturbation energy samples per replica has been collected. The simulation will stop whenever the WALL_TIME or MAX_SAMPLES conditions are met. So you could set WALL_TIME to a very large number and let AToM run as long as it takes to collect a desired number of samples (per replica).

The speed reporting, like ns/day, could be implemented by starting a timer when a replica is launched and stopping it when it completes. The physical time (ns) can be calculated by the given number of steps and the MD time-step. The ratio of the two is what you probably want. There is a slight complication that "launching" a replica does not actually execute the replica on the GPU. Instead, it places it into a queue. Replicas are taken from this queue when a GPU is idle. Of course, you can always calculate the throughput in post-processing using the number of samples acquired (from the `*_stat.txt` file, for example) and the execution time.

**Comment by smutao** [comment]
> WALL_TIME is the maximum wall-clock time in minutes that the simulation will run for.
> 
> PRODUCTION_STEPS is the number of MD steps each replica will run for before checkpointing and exchanging with other replicas.
> 
> TIME_STEP is the MD time-step in ps
> 
> There is a parameter (MAX_SAMPLES) that I don't think we mention in the tutorials that stops the simulation if the given number of perturbation energy samples per replica has been collected. The simulation will stop whenever the WALL_TIME or MAX_SAMPLES conditions are met. So you could set WALL_TIME to a very large number and let AToM run as long as it takes to collect a desired number of samples (per replica).
> 
> The speed reporting, like ns/day, could be implemented by starting a timer when a replica is launched and stopping it when it completes. The physical time (ns) can be calculated by the given number of steps and the MD time-step. The ratio of the two is what you probably want. There is a slight complication that "launching" a replica does not actually execute the replica on the GPU. Instead, it places it into a queue. Replicas are taken from this queue when a GPU is idle. Of course, you can always calculate the throughput in post-processing using the number of samples acquired (from the `*_stat.txt` file, for example) and the execution time.

Hello Professor Gallicchio, I have a question about MAX_SAMPLES variable: How can we convert MAX_SAMPLES to the total simulation time (e.g. 10ns) for each replica like you did in your paper (J. Chem. Inf. Model. 2022, 62, 309−323)? 

Thank you very much.

**Comment by egallicc** [comment]
PRNT_FREQUENCY = number of MD steps in between saving of perturbation energy samples to disk

So:

number of MD steps per replica = MAX_SAMPLES * PRNT_FREQUENCY

For example, if MAX_SAMPLES = 200 and PRNT_FREQUENCY = 10000, each replica will perform 2x10<sup>6</sup> MD steps or 4 ns with a 2 fs time-step.

(Documentation and cleaning up of the control file syntax are long overdue!)

**Comment by smutao** [comment]
> There is a parameter (MAX_SAMPLES) that I don't think we mention in the tutorials that stops the simulation if the given number of perturbation energy samples per replica has been collected. The simulation will stop whenever the WALL_TIME or MAX_SAMPLES conditions are met. So you could set WALL_TIME to a very large number and let AToM run as long as it takes to collect a desired number of samples (per replica).

Thanks a lot. This is helpful!

**Comment by smutao** [comment]
Recently, I did some RBFE calculation on HSP90 system (~30k atoms in 67x67x67 A^3 box).

I used the following three keywords trying to run  6 ns for each out of 22 replica (in total 132 ns). 

```
PRNT_FREQUENCY = '20000'
MAX_SAMPLES = '150'
TIME_STEP = 0.002
```

[full .cntl file is attached]

It took me about 45 hours to complete the production run (speed is around 2.9 ns/hr). Is this speed normal? I used one NVIDIA RTX A5000 card.

Thank you in advance. 

[sample.cntl.txt](https://github.com/Gallicchio-Lab/AToM-OpenMM/files/12793913/sample.cntl.txt)

**Comment by egallicc** [comment]
I am not sure. AToM's performance is directly linked to OpenMM's performance. See: https://openmm.org/benchmarks

Consider that ATM computes energy and forces twice at each MD step. In addition, the system's coordinates are transferred between GPU buffers before each energy/forces evaluation. AToM's throughput is also affected by latencies in moving replicas in and out of the GPU. The latter is affected by how often replicas are cycled and the speed of the PCI bus, among other things. 

If the card is not utilized near 100%, try increasing PRODUCTION_STEPS to decrease the number of cycles of replicas in and out of the GPU.In some case, the system is be too small to fully utilize all of the hardware threads of the card.

With HMASS=1.5 amu, you can safely increase TIME_STEP to 0.004 ps.

**Comment by smutao** [comment]
> I am not sure. AToM's performance is directly linked to OpenMM's performance. See: https://openmm.org/benchmarks
> 
> Consider that ATM computes energy and forces twice at each MD step. In addition, the system's coordinates are transferred between GPU buffers before each energy/forces evaluation. AToM's throughput is also affected by latencies in moving replicas in and out of the GPU. The latter is affected by how often replicas are cycled and the speed of the PCI bus, among other things.
> 
> If the card is not utilized near 100%, try increasing PRODUCTION_STEPS to decrease the number of cycles of replicas in and out of the GPU.In some case, the system is be too small to fully utilize all of the hardware threads of the card.
> 
> With HMASS=1.5 amu, you can safely increase TIME_STEP to 0.004 ps.

Many thanks for your suggestion on 'PRODUCTION_STEPS' parameter. I will try to use 4-fs time step.
