### ISSUE TITLE
Preemption and checkpointing on GPUGRID

### ISSUE THREAD

**Issue by egallicc** [Gallicchio-Lab/AToM-OpenMM#29]
Dear @raimis: 

There has been some [discussion](https://www.gpugrid.net/forum_thread.php?id=5379) on the GPUGRID forum regarding preemption and checkpointing support for ATM, among other issues.

The standard asynchronous version of AToM catches termination signals to call the checkpointing routine. The synchronous version does not appear to do that.

It is also unclear whether GPUGRID's app passes termination signals to the backend. 

Could you please comment? I think it is important that AToM exits cleanly when GPUGRID tasks are preempted. Thanks.

**Comment by raimis** [comment]
Yes, I'm aware of the issues on GPUGRID and we are trying to fix them.
