### ISSUE TITLE
Repeat times for each system

### ISSUE THREAD

**Issue by researchhh** [Gallicchio-Lab/AToM-OpenMM#30]
Hi,

I used AToM for relative binding free energy calculation for several systems, and the results are pretty good. I am wondering how many independent runs you guys performed for each system presented in the paper (https://pubs.acs.org/doi/10.1021/acs.jcim.1c01129). 

Thank you!!

**Comment by egallicc** [comment]
Thank you for providing feedback.

We did not explicitly perform repeats in that paper. 

I have my own opinions on what an "independent repeat" is or should be.

Happy to discuss science topics elsewhere.  This forum is about the software package. Thanks.

**Comment by researchhh** [comment]
Thanks for your reply. I have another question related to the UWHAM package.  I used ./analyze.sh to obtain the ddG values and error bars. I checked the UWHAM-package document, it seems like the variance estimation is based on the Fisher information or Sandwich variance formula. I would like to double-check with you about the variance estimation calculation in uwham_analysis.R. 

Thank you!!
