### ISSUE TITLE
OpenCL error

### ISSUE THREAD

**Issue by chaoyangma24** [Gallicchio-Lab/AToM-OpenMM#32]
Thank for ATom-OpenMM
When I run "python mintherm.py && python npt.py && python equil.py" , there appeared the following wrongs. Your reply wound be very appreciated.
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Started at: Sun Apr 30 11:03:26 2023
Traceback (most recent call last):
  File "mintherm.py", line 58, in <module>
    platform = Platform.getPlatformByName(platform_name)
  File "/home/chaoyang/miniconda3/envs/atm/lib/python3.7/site-packages/openmm/openmm.py", line 18453, in getPlatformByName
    return _openmm.Platform_getPlatformByName(name)
openmm.OpenMMException: There is no registered Platform called "OpenCL"

**Comment by egallicc** [comment]
OpenMM cannot find an OpenCL installation. Are the OpenMM tests successful on your machine? (see [openmm.org](https://openmm.org/documentation).)

**Comment by chaoyangma24** [comment]
Dear Professor&nbsp;Emilio&nbsp;Gallicchio
&nbsp;Thank for your kind reply! According to your recommendation, I can run these "*.py"s, after make the following corresponding modifications.&nbsp;
&nbsp;
platform_name = 'CPU'
#platform_name = 'CUDA'
platform = Platform.getPlatformByName(platform_name)
properties = {}
#properties["Precision"] = "mixed"


Best regards&nbsp;
Dr Ma
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, May 1, 2023 09:25 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [Gallicchio-Lab/AToM-OpenMM] OpenCL error (Issue #32)

&nbsp;



 
OpenMM cannot find an OpenCL installation. Are the OpenMM tests successful on your machine? (see openmm.org.)

**Comment by egallicc** [comment]
This test indicates that your machine does not have an OpenCL-capable GPU, or that it is misconfigured.
