### ISSUE TITLE
about v4.0.0rc branch (OpenMM vs AMBER input data format)

### ISSUE THREAD

**Issue by smutao** [Gallicchio-Lab/AToM-OpenMM#37]
Dear Professor Gallicchio,

I found the v4.0.0rc branch is adopting the OpenMM data format as the input to run AToM simulation rather than the AMBER format input. Is AToM going to obsolete the AMBER input gradually in future? 

Thank you very much.

**Comment by egallicc** [comment]
Yes, the 4.0 branch is an attempt to standardize the input as an OpenMM's serialized System file (.xml). 

We provide a [script](https://github.com/Gallicchio-Lab/AToM-OpenMM/blob/v4.0.0rc/make_atm_system_from_Amber.py) to convert Amber files into a serialized OpenMM System. Amber file support is expected to continue in this manner.

The new system introduces support for OpenFF-based force fields and any other setup workflow that yields an XML OpenMM System file.
