### ISSUE TITLE
How to understand Rplots.pdf?

### ISSUE THREAD

**Issue by 9527567** [Gallicchio-Lab/AToM-OpenMM#42]

**Comment by egallicc** [comment]
Can you be more specific? Sorry, our documentation is incomplete, and we have multiple R scripts floating around for different purposes.

**Comment by egallicc** [comment]
Those two plots show the probability distributions of the perturbation energy for the two alchemical legs. To establish the quality of the calculation, we generally look for an unbroken sequence of overlapping distributions. The first leg is okay. However, the second has a break at 150 kcal/mol and it is probably not converged.

The jaggedness of the distributions signals that only a few samples were collected. Probably an insufficient number for a good estimate of the free energy.

Can you please tell us where you found the script that generated the graph you posted? I see that it needs work. The axes are not labeled properly and have no units.

**Comment by 9527567** [comment]
Use the script here. `AToM-OpenMM/examples/ABFE/fkbp/scripts/uwham_analysis.R`
Can you display a suitable Rplots? Thank you.

**Comment by egallicc** [comment]
We will try to improve the scripts we post in this repo. But feel free to change it yourself to suit your needs. That is why we distribute source code. So that people can change, improve, and customize it. We welcome PR with improvements

**Comment by 9527567** [comment]
Thank you, I will carefully read and understand your code.This is a great job.

**Comment by 9527567** [comment]
I have a few more questions for your guidance.
[fig.zip](https://github.com/Gallicchio-Lab/AToM-OpenMM/files/13222811/fig.zip)

These two figures are ligands from a certain experiment I conducted, and their ABFE matches the experiment very well with an error of only **0.02**. However, what I want to know is that at 150kcal/mol, the second figure does not perform very well, so is this an **occasional** match?

The second question is, does the 150kcal/mol-200kcal/mol in the second graph not overlap, indicating that the second path is not very suitable? If there is a need to adjust the path, is there a better adjustment direction?

Thank you very much.

**Comment by FlorisLoffler** [comment]
Are there any plans as of yet to update the Rplots.pdf, so they show the correct axes? Furthermore, the x-axis shows values in kcal/mol, but this also seems to coincide with the reaction parameter lambda, right? So could the axis also be in lambda?
