### ISSUE TITLE
Disconnected alchemical path

### ISSUE THREAD

**Issue by egallicc** [Gallicchio-Lab/AToM-OpenMM#47]
I have a few more questions for your guidance.
[fig.zip](https://github.com/Gallicchio-Lab/AToM-OpenMM/files/13222811/fig.zip)

These two figures are ligands from a certain experiment I conducted, and their ABFE matches the experiment very well with an error of only **0.02**. However, what I want to know is that at 150kcal/mol, the second figure does not perform very well, so is this an **occasional** match?

The second question is, does the 150kcal/mol-200kcal/mol in the second graph not overlap, indicating that the second path is not very suitable? If there is a need to adjust the path, is there a better adjustment direction?

Thank you very much.

_Originally posted by @9527567 in https://github.com/Gallicchio-Lab/AToM-OpenMM/issues/42#issuecomment-1788311206_

**Comment by egallicc** [comment]
The sequence of probability densities of the perturbation energy indicates that the alchemical path is disconnected. There are regions where the probability densities do not overlap. The resulting free energy estimate cannot be trusted.

We often see this behavior when the perturbation is too large. In our experience, ABFEs with ligands with more than 10-15 heavy atoms fail in this way. Unless there are other issues, I recommend breaking up the binding into smaller steps. [Here is an example](https://doi.org/10.1039/D3CP02125D).

**Comment by 9527567** [comment]
Thank you, I will try.
