### ISSUE TITLE
Is it necessary to customize the following parameters for different systems?

### ISSUE THREAD

**Issue by 9527567** [Gallicchio-Lab/AToM-OpenMM#48]
`CM_KF = 25.00`
`CM_TOL = 5.00`

`POSRE_FORCE_CONSTANT = 25.0`
`POSRE_TOLERANCE = 0.5`

`UMAX = 200.00`
`ACORE = 0.062500`
`UBCORE = 100.0`

`FRICTION_COEFF = 0.500000`

Regarding ABFE, are the above parameters a universal choice or tend to be customized for different systems?

**Comment by egallicc** [comment]
All these settings can and should be specifically considered depending on the system at hand. Some affect the accuracy of the model, and others the time to convergence.  Some of these settings encapsulate statistical mechanics formalisms that are too complex to summarize here. Please consult our ATM [papers](https://www.compmolbiophysbc.org/publications) and [documentation](https://www.compmolbiophysbc.org/atom-openmm).  The Langevin friction coefficient is an MD setting unrelated to the alchemical transformation.

**Comment by 9527567** [comment]
Thank you, I will read these articles carefully.
