### ISSUE TITLE
On ligand reference atom selection

### ISSUE THREAD

**Issue by qsabanes** [Gallicchio-Lab/AToM-OpenMM#5]
Hi again, 
I've seen that with the new protocol you uploaded the selection of restraining atoms for the ligands seem to be more "unforgiving". In many cases I've seen that by the end of the annealing step the ligand has shifted considerably from the starting position, both in displacement and/or atom torsion leading to really poor values (>15kcal/mol in RBFE). Although I sometimes managed to select a series of atoms that do not lead to this issue I was wondering if there is any set of guidelines you follow in regards to that process.

Furthermore, I had another question regarding sampling and how it is saved. In the temoa-g1 tutorial you can read the following:

> The .out file of each replica is in the following sample format where each line is a sample (saved every 5ps in this case),

In that case we can see in the .cntl file the following related flags:
PRODUCTION_STEPS = '5000'
PRNT_FREQUENCY = '5000'

Which I believe PRNT_FREQUENCY corresponds to the aforementioned 5 ps right? And if I understand correctly this is not affected by the chosen timestep? And then every sample/line in the CDK2 example were PRNT_FREQUENCY and PRODUCTION_STEPS corresponds to '20000' would be 20ps right? I am used to work in (time)steps and this is confusing me a bit.

Many thanks again
Quico

**Comment by egallicc** [comment]
Hi Quico. Do you observe this shift for the CDK2 example itself or a system templated on it? The definition of the binding site is system dependent. The centroid of the 'vsite_rcpt_residues` in `setup-settings.sh` should be near the centroid of the ligands. 

For the CDK2 example, we defined the centroid of the ligand as the position of the [first reference atom](https://github.com/Gallicchio-Lab/AToM-OpenMM/blob/a9547b65c60d5a74c85994b0c89fff36313a3157/examples/RBFE/cdk2/scripts/setup-atm.sh#L193). This choice usually gives more fine control relative to using the centroid based on all atoms of the ligand, which moves around depending on the size and shape of each ligand.

Another setting is the maximum distance allowed between the two centroids (`tol` in `mintherm_template.py` and `mdlambda_template.py`, and `CM_TOL` in `asyncre_template.cntl`) . You can increase this threshold when necessary. For example, when the ligands do not align well. Relative binding free energies between strong binders, which remain in the binding site regardless,  are not affected significantly by the specific definition of the binding site. It is often okay to use a large threshold.

**Comment by egallicc** [comment]
Despite their names, `PRODUCTION_STEPS`, `PRNT_FREQUENCY`, and `TRJ_FREQUENCY` are all specified in terms of the number of MD steps. A separate keyword `TIME_STEP` specifies the time step in ps. In the CDK2 example `TIME_STEP = 0.002` ps, so if `PRNT_FREQUENCY = 20000` steps, samples are saved once every 40 ps.

**Comment by qsabanes** [comment]
Hi Emilio, 
I did not see a tight overlap for some of the ligands in the CDK2 example but simulations did not give any problems and results came back good. It's just that for some of my cases the overlap was really poor. Even so in some cases with good alignment I was getting poor RBFE values, so maybe there's something wrong with my setup.
I define the binding site by choosing the nearby residues around the ligand but I'll check with the setup you propose.

Regarding the time-step, that's what I thought. Am I mistaken if then in the tutorial the sample size is 10ps? Since   `TIME_STEP = 0.002` and `PRNT_FREQUENCY = 5000`. 

Thanks!

**Comment by egallicc** [comment]
I might have misunderstood the question. Is it about the choice of reference atoms of the ligands to keep them aligned during the simulation?

**Comment by egallicc** [comment]
Choosing the binding site residues as those closest to the ligand is often okay, but in some cases the distribution of residues is asymmetric and their centroid falls far away from the ligand.

**Comment by egallicc** [comment]
> Regarding the time-step, that's what I thought. Am I mistaken if then in the tutorial the sample size is 10ps? Since TIME_STEP = 0.002 and PRNT_FREQUENCY = 5000.

Correct.

**Comment by egallicc** [comment]
Maybe upload or send me an example of the structures you have trouble with in terms of ligand reference atoms and/or binding site residue selection. Looking at specific examples can probably illuminate the issues better.

**Comment by qsabanes** [comment]
Yes, I meant about the reference atoms for the ligands. I modified the tolerance values in `mdlambda.py` and `asyncre_template.cntl` and for now it seems to work fine.

The changes were the following:
In `mdlambda.py`
from `tol = 1.5 * angstrom` to `tol = 2.5 * angstrom`
In `asyncre_template.cntl`
from `CM_TOL = 5` to `CM_TOL = 10`

**Comment by egallicc** [comment]
Sorry, we need to clean up these keywords and integrate the system preparation scripts into the main code to avoid duplication. In the meantime, note that:

- `tol` in `mdlambda.py` is the tolerance of the flat-bottom positional restraint on the receptor C-alpha atoms. It is okay to change it if needed, but for consistency, set the corresponding quantity (POSRE_TOLERANCE) in `asyncre_template.cntl` to the same value.
- `CM_TOL` is the radius of the binding site volume, which is the maximum allowed distance between the CM of the receptor and the CM of the ligand. The corresponding quantity in `asyncre_template.cntl` is called `r0`. If you change one, set the other to the same value. If increasing CM_TOL from 5 to 10 resolves the issue, it is likely that the CM of the binding site residues falls far away from the CM of the ligand. In any case, as we discussed above, it is often safe in RBFE calculations to ignore the binding site definition by setting, for example, CM_TOL to some very large value.
- The settings above are unrelated to the choice of reference atoms of the ligands used to keep the ligand pair aligned. In most cases, it is sufficient to choose three non-colinear reference atoms in a rigid portion of each ligand that are aligned to three reference atoms of the other. The sequence of the reference atoms matter.

**Comment by stefdoerr** [comment]
@egallicc Hi, I was also wondering a bit about the selection of the three alignment atoms between the two ligands. What is the ideal selection and how does it affect the RBFE calculations? If you have two large flexible ligands would it be good enough to align them on three atoms of a single aromatic ring and leave the rest to rotate freely?

From the paper I find these quotes:

> Here we also introduce a restraining potential that maintains ligand alignment in order to enhance the convergence of the calculations for similar ligand pairs and we show mathematically that these calculations yield unbiased binding free energy estimates.

> For ligands with similar shape, the occurrences of severe clashes with nearby atoms would be considerably reduced if the two ligands land in a similar location and orientation when their positions are swapped.  In order to improve convergence, we therefore introduce restraint potentials that help to maintain the positions and orientations of the two ligands in approximate alignment. 

This would indicate that choosing a single ring in a large ligand would slow down convergence significantly due to clashes. However if the ligands are significantly different, aligning on three atoms distributed all over the ligand (let's say two atoms on the total extremes of the molecule and one atom in the COM) could keep the ligands from interacting correctly with the binding site.
