### ISSUE TITLE
Do you have any plans to include other restraints methods in the configuration file？

### ISSUE THREAD

**Issue by 9527567** [Gallicchio-Lab/AToM-OpenMM#51]
I see that other constraint methods have been implemented [here](https://github.com/Gallicchio-Lab/AToM-OpenMM/blob/fd9380d533a699cf15066d3bc0077028ad9fb916/utils/AtomUtils.py#L275), but they do not seem to be enabled.

**Comment by egallicc** [comment]
Right, we implemented Boresch-style binding site restraints but we never tested them and we dot use them.

We have developed our own binding mode orientational restraints that, as far as I know, have been used in only one production project:

https://github.com/Gallicchio-Lab/SAMPL9-bCD

So they are there, but as with many other features, we are behind in terms of documentation. Let us know if the examples above plus the paper referenced are sufficient to get started.

**Comment by 9527567** [comment]
Thank you, I will try.
