### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by sobertie** [Gallicchio-Lab/AToM-OpenMM#53]
Hello everyone, I am currently using AToM-OpenMM for estimating relative binding energy of FT895 and Elevenostat molecules for HDAC11. Whenever I run prep.sh shell file, it is showing following error -
Traceback (most recent call last):
  File "/home/mohon/AToM-OpenMM/rbfe_structprep.py", line 426, in <module>
    massage_keywords(keywords, restrain_solutes)
  File "/home/mohon/AToM-OpenMM/rbfe_structprep.py", line 396, in massage_keywords
    nlig2 = len(keywords.get('LIGAND2_ATOMS'))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

Is there any solution for this ?

**Comment by sobertie** [comment]
Here is my control file.
[FEP.zip](https://github.com/Gallicchio-Lab/AToM-OpenMM/files/13347866/FEP.zip)

**Comment by egallicc** [comment]
I don't see a control file in the `complexes/hdac11-FT895H-ElevenostatH/` folder. So maybe the error is just due to a missing control file?

**Comment by egallicc** [comment]
Tentatively closing. Re-open if it is not resolved.
