### ISSUE TITLE
Would you consider licensing this code under the MIT License to be consistent with OpenMM?

### ISSUE THREAD

**Issue by jchodera** [Gallicchio-Lab/AToM-OpenMM#57]
@egallicc : Would you consider making this code available under the less restrictive [MIT License](https://opensource.org/license/mit/) to be consistent with OpenMM?

**Comment by egallicc** [comment]
Hi. I don't know if I can. The AsyncRE code originates from ca. 2010 during the Rutgers days, and it would be nearly impossible to track down all of the original developers. I am not even sure when the GPL license was first attached to the project.

But should we even consider it? Eventually, we would like the AToM-OpenMM effort to flow into OpenFE. Towards that goal, the main Alchemical Transfer technology (ATMForce) is already part of OpenMM, and there are probably significantly better alternatives to AToM's system setup scripts. That leaves only the ASyncRE job transport and replica exchange algorithms as potentially useful codebases. 

Historically, Asynchronous Replica Exchange job transport took many forms, including for grid computing, but we only implemented a rather rudimentary multiprocessing option with OpenMM. For replica exchanges, we use what we call a restricted Gibbs permutation algorithm that can be easily implemented elsewhere if needed.

In addition, while we like Asynchronous RE a lot, I know of a couple of ATM corporate efforts that are humming along just fine with plain synchronous RE. One of these efforts could be a promising platform to build upon. Let's discuss offline.

**Comment by jchodera** [comment]
Thanks for the thoughtful response! I'll reach out via email.
