### ISSUE TITLE
Can we use MPI to distribute computing?

### ISSUE THREAD

**Issue by 9527567** [Gallicchio-Lab/AToM-OpenMM#59]
Perhaps we can transform it into MPI? This can fully leverage the computing power of the cluster. What I understand is that for each `ommworker`, an mpi process can be assigned. According to my understanding, most of the modifications will be carried out on `ommworker.py`. I am willing to try this job. Do you have any suggestions?

**Comment by egallicc** [comment]
Yes, that would be a great enhancement for AToM-OpenMM!

The management of worker processes is currently implemented with the Python multiprocessing module, which is limited to devices on the same host. An MPI job transport implementation would allow worker processes on remote machines as well.

MPI is most often used for synchronous parallel computing. However, AToM-OpenMM is based on the [asynchronous](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4834714/) version of the replica exchange algorithm. Asynchronous RE has a number of advantages, such as the ability to utilize efficiently computing devices of different speeds and recover from software/hardware failures. We want to retain the asynchronous feature.

MPI can be used for asynchronous parallel computing by implementing a queue of controlling commands and asynchronous data transfers or equivalent, similar to the current Python multiprocessing implementation. The work would entail translating the host/worker communication routines `run()`, `set_posvel()`, etc. in `ommworker.py` to MPI calls. The `OMMWorker` `__init__` routine would have to be modified to initialize the MPI environment. The hostnames of the remote computing machines are already available from the `nodefile` and stored in `node_info['node_name']`. I don't think there would be changes to `local_openmm_transport.py` if MPI calls are abstracted by  `run()`, `set_posvel()`, etc. methods in `ommworker.py`. However, this file should be probably renamed `openmm_transport.py` or similar to avoid confusion.

I believe that recent versions of `mpi4py` support dynamics process management to restart failed workers, etc. But maybe dynamic process management and restart routines could be implemented at a later stage.

**Comment by 9527567** [comment]
Thank you very much, I will try my best.
