### ISSUE TITLE
What does LIGOFFSET mean?

### ISSUE THREAD

**Issue by 9527567** [Gallicchio-Lab/AToM-OpenMM#61]
If it is not [0, 0, 0], does it mean that the ligand is not in the center of the pocket and has shifted? Is this a repair for the above situation?

**Comment by egallicc** [comment]
It is a rarely-used option. It shifts the binding site restraint by the given amount.

Longer explanation. The binding site region is usually defined by a flat-bottom harmonic distance restraint between the centroid of the receptor binding site and the centroid of the ligand. Additionally, LIGOFFSET is subtracted from the centroid of the ligand before the restraint is applied.

As far as I know, this option has been used only to perform ABFE calculations starting with the ligand in solution (in which case LIGOFFSET = DISPLACEMENT), but it could also be used to fine-tune the placement of the binding site region.

**Comment by 9527567** [comment]
Thank you, it's very clear.
