### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by sobertie** [Gallicchio-Lab/AToM-OpenMM#62]
Hi everyone, I am currently working on ABFE of HDAC11 molecule with its known and prospective inhibitors from ZINC database. My ligands are FT895, ZN125, ZN136, ZN159, ZN240 and ZN307. But whenever i tried to run the command "bash ./scripts/setup-atm.sh", i get the following error "Processing ligand  FT895 ZN125 ZN136 ZN159 ZN240 ZN307...
./scripts/setup-atm.sh: line 25: cd: /home/mohon/AToM-OpenMM/examples/ABFE/FEP/complexes/hdac11-FT895 ZN125 ZN136 ZN159 ZN240 ZN307: No such file or directory".
What should I do now ?

**Comment by joezwu** [comment]
Can you post your `setup-settings.sh` file?

**Comment by sobertie** [comment]
My setup-settings.sh file is like this:

#basename for jobs
basename=hdac11

#path to ASyncRE
asyncre_dir=$HOME/software/async_re-openmm

#basename of the receptor pdb file (processed for amber using pdb4amber)
receptor=hdac11

#basenames of the ligand pairs (.mol2 format expected)
#with their reference alignment atoms
  ligands=("FT895 ZN125 ZN136 ZN159 ZN240 ZN307")
ref_atoms=("22,9,5 22,9,5")

#displacement vector
displacement=("23.0" "23.0" "23.0")

#residue ids of the receptor that define the center of the binding site
vsite_rcpt_residues=(96 132 133 136 143 144 145 176 177 179 180 254 295 297)

**Comment by egallicc** [comment]
The format of the `ligands` specification is incorrect. See the [CDK2 setup_settings.sh example](https://github.com/Gallicchio-Lab/AToM-OpenMM/blob/master/examples/RBFE/cdk2/scripts/setup-settings.sh).
