### ISSUE TITLE
Cannot convert from 'angstrom' to 'dimensionless'

### ISSUE THREAD

**Issue by sobertie** [Gallicchio-Lab/AToM-OpenMM#64]
Hello everyone, I am running abfe of HDAC11 molecule with prospective ligands. Whenever I run the command "bash ./scripts/setup-atm.sh", it is giving me the following error:

Processing ligand  FT895...
Generate ATM RBFE OpenMM System

Date and time at start:  Thu Dec  7 13:59:30 2023

User-supplied input parameters
Receptor file name:                  /home/mohon/AToM-OpenMM/examples/ABFE/FEP/receptor/hdac11.pdb
Protein force field:                 amber14-all.xml
Solvent/ion force field              amber14/tip3p.xml
Ligand force field:                  openff-2.0.0
Ligand 1 file name:                  /home/mohon/AToM-OpenMM/examples/ABFE/FEP/ligands/FT895.sdf
Topology PDB output file:            hdac11-FT895.pdb
System XML output file:              hdac11-FT895_sys.xml
Force field cache file:              /home/mohon/AToM-OpenMM/examples/ABFE/FEP/ligands/ffdb.json
Call ForceField for protein and water
Receptor in PDB format
Number of atoms in receptor: 5120
Call Modeller: include receptor
Calculating receptor bounding box:
Areas of faces [Quantity(value=31.7177582, unit=nanometer**2), Quantity(value=27.182023209999997, unit=nanometer**2), Quantity(value=30.5850878, unit=nanometer**2)]
Direction of smallest area dimention: 2
Read ligand 1:
Number of atoms in ligand 1: 40
Call Modeller: include ligand 1
Indexes of ligand 1 (starting from 0): [5120, 5121, 5122, 5123, 5124, 5125, 5126, 5127, 5128, 5129, 5130, 5131, 5132, 5133, 5134, 5135, 5136, 5137, 5138, 5139, 5140, 5141, 5142, 5143, 5144, 5145, 5146, 5147, 5148, 5149, 5150, 5151, 5152, 5153, 5154, 5155, 5156, 5157, 5158, 5159]
Traceback (most recent call last):
  File "/home/mohon/AToM-OpenMM/make_atm_system_from_rcpt_lig.py", line 304, in <module>
    lig1_positions[i] += displacement
  File "/home/mohon/anaconda3/envs/atm/lib/python3.12/site-packages/openmm/unit/quantity.py", line 239, in __add__
    value = self._value + other.value_in_unit(self.unit)
            ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  File "/home/mohon/anaconda3/envs/atm/lib/python3.12/site-packages/openmm/vec3.py", line 51, in __add__
    return Vec3(self.x+other[0], self.y+other[1], self.z+other[2])
                ~~~~~~^~~~~~~~~
  File "/home/mohon/anaconda3/envs/atm/lib/python3.12/site-packages/pint/facets/plain/quantity.py", line 1188, in __add__
    return self._add_sub(other, operator.add)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohon/anaconda3/envs/atm/lib/python3.12/site-packages/pint/facets/plain/quantity.py", line 108, in wrapped
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohon/anaconda3/envs/atm/lib/python3.12/site-packages/pint/facets/plain/quantity.py", line 1086, in _add_sub
    raise DimensionalityError(self._units, "dimensionless")
pint.errors.DimensionalityError: Cannot convert from 'angstrom' to 'dimensionless'

How to circumvent the following error ?

**Comment by egallicc** [comment]
I have seen this error with older versions of AToM-OpenMM and particular versions of `openmmforcefields`. Please confirm that you have the latest version of AToM-OpenMM (`git pull`).

**Comment by egallicc** [comment]
I assume this is addressed? Reopen the issue if it isn't.
