### ISSUE TITLE
about alchemical scheme parameters in control file

### ISSUE THREAD

**Issue by smutao** [Gallicchio-Lab/AToM-OpenMM#65]
Dear Professor Gallicchio,

While using AToM, I realized that there are two versions of control files in terms of the parameters including  LAMBDA1, LAMBDA2, ALPHA, U0, UMAX and UBCORE. 

In RBFE eralpha example and ABFE examples, one version was used. 
https://github.com/Gallicchio-Lab/AToM-OpenMM/blob/master/examples/RBFE/eralpha/scripts/asyncre_template.cntl
https://github.com/Gallicchio-Lab/AToM-OpenMM/blob/master/examples/ABFE/fkbp/scripts/asyncre_template.cntl 

In RBFE cdk example and Eric Chen's example, another version was used. 
https://github.com/Gallicchio-Lab/AToM-OpenMM/blob/master/examples/RBFE/cdk2/scripts/asyncre_template.cntl
https://github.com/EricChen521/ATM_MerckSet

Should we use the latter version in future? 

Thanks a lot.

**Comment by egallicc** [comment]
The alchemical schedule and soft-core perturbation energy settings are (ideally) adjusted for each system to achieve an optimal convergence rate. This usually entails checking in `Rplots.pdf` that the sequence of the perturbation energy's distribution functions is connected.

The ones you mention are considered good general-purpose settings based on our experience. It's still a topic of research, but anecdotally, the first two schedules are okay for "easy" transformations, and the second two are for more challenging transformations.

These are our main theory papers on the subject:

Rajat K. Pal and Emilio Gallicchio. Perturbation Potentials to Overcome Order/Disorder Transitions in Alchemical Binding Free Energy Calculations. J. of Chem. Phys.. 151, 124116 (2019). Featured Article. [doi:10.1063/1.5123154](https://doi.org/10.1063/1.5123154) [Arxiv](https://arxiv.org/abs/1907.06636)

Sheenam Khuttan, Solmaz Azimi, Joe Z. Wu, and Emilio Gallicchio. Alchemical Transformations for Concerted Hydration Free Energy Estimation with Explicit Solvation. J. Chem. Phys. 154, 054103 (2021). [doi:10.1063/5.0036944](https://doi.org/10.1063/5.0036944)  [pdf](https://www.compmolbiophysbc.org/publications/jcp2021a)

**Comment by smutao** [comment]
Thank you very much for the answer and suggestions. It is very helpful.
