### ISSUE TITLE
Continuing discussion on speed.

### ISSUE THREAD

**Issue by 9527567** [Gallicchio-Lab/AToM-OpenMM#69]
In this submission https://github.com/Gallicchio-Lab/AToM-OpenMM/commit/be867de26bbf638576dc8c7db07167abf0f7e64a, the code has been effective in improving speed. But unfortunately, MD crashed.
This is a log [std.log](https://github.com/Gallicchio-Lab/AToM-OpenMM/files/14007936/std.log) of code running with improved code speed, and it can be seen that MD quickly encountered a crash.

This is the original code running [std.log](https://github.com/Gallicchio-Lab/AToM-OpenMM/files/14007913/std.log), I only intercepted a part of the front, it can run correctly.

**Comment by egallicc** [comment]
Yes, I have been seeing failures as well with the latest trick #be867de of retaining the nonbonded force in the System.  Somehow the reordering of the atoms it triggers is not communicated correctly to the rest of the code.

I am seeing this only during replica exchange. Have you ever seen failures during structure preparation?

**Comment by 9527567** [comment]
The structural preparation stage is completely normal! And the acceleration effect is very obvious.

**Comment by egallicc** [comment]
Thanks. I have fixed an issue with the energy reported in the .out files. 

I have fixed the random crashes with the faster code as well. But that will have to wait for an OpenMM PR to be approved, incorporated, and released. In the meantime, please continue to use the [v8.1.0 release](https://github.com/Gallicchio-Lab/AToM-OpenMM/releases/tag/v8.1.0) even though it's not fast.

**Comment by egallicc** [comment]
It turns out that the crashes were likely fixed in OpenMM 8.1.1. Please try the latest AToM-OpenMM v8.1.1 release that works with OpenMM v8.1.1

**Comment by 9527567** [comment]
Thank you, I will try a new version.
