### ISSUE TITLE
The parameters for dynamic sampling and analysis are different in ABFE temoa-g1.

### ISSUE THREAD

**Issue by 9527567** [Gallicchio-Lab/AToM-OpenMM#70]
In this example, I observed that the parameters in the cntl file are inconsistent with those in the analysis script. Is there any special reason for this? 
https://github.com/Gallicchio-Lab/AToM-OpenMM/blob/61c3c03a25c5aec2c9ccaf7ad5f0f25f4a97658e/examples/ABFE/temoa-g1/temoa-g1_asyncre.cntl#L12-L19

https://github.com/Gallicchio-Lab/AToM-OpenMM/blob/61c3c03a25c5aec2c9ccaf7ad5f0f25f4a97658e/examples/ABFE/temoa-g1/uwham_analysis.R#L80-L88

**Comment by egallicc** [comment]
It's a bug! Could you please fix it in a PR? The non-linear schedule in the control file should replace the linear one uwham_analysis.R script. Thanks.

**Comment by 9527567** [comment]
Thank you, I will resolve this bug in a PR.
