### ISSUE TITLE
setup-setttings.sh modification.

### ISSUE THREAD

**Issue by sobertie** [Gallicchio-Lab/AToM-OpenMM#71]
I am using HDACC11 protein as receptor and some prospective small molecule as ligands. I understand that I need to change the setup-settings.sh file. My current file looks like this -

#basename for jobs
basename=hdac11

#basename of the receptor pdb file (processed for amber using pdb4amber)
receptor=hdac11

#basenames of the ligands (.mol2 format expected)
ligands=(ZN125 ZN136 ZN159 ZN240 ZN307)

#displacement vector
displacement=("22.0" "22.0" "22.0")

#residue ids of the receptor that define the center of the binding site
vsite_rcpt_residues=(318)

#path to AToM-OpenMM
AToM_dir=$HOME/AToM-OpenMM

I understand I need to change the displacement vector. Otherwise I am getting this error - 

python /home/mohon/AToM-OpenMM/examples/ABFE/FEP/scripts/create_cntlfile_from_template.py --systemPDBFile hdac11-ZN125.pdb --templatein /home/mohon/AToM-OpenMM/examples/ABFE/FEP/scripts/asyncre_template.cntl --jobname hdac11-ZN125 --displacement  22.0 22.0 22.0 --lig1resname L1 --vsiteResidues 318 
Traceback (most recent call last):
  File "/home/mohon/AToM-OpenMM/examples/ABFE/FEP/scripts/create_cntlfile_from_template_abfe.py", line 82, in <module>
    l = l.replace('<VSITERECEPTORATOMS>', list_to_string(vsite_atoms))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohon/AToM-OpenMM/examples/ABFE/FEP/scripts/create_cntlfile_from_template_abfe.py", line 35, in list_to_string
    s = str(alist[0])
            ~~~~~^^^
IndexError: list index out of range

How to determine displacement vector for this protein molecule ?

**Comment by egallicc** [comment]
It looks like `create_cntlfile_from_template_abfe.py` assumes that there is a list of two or more receptor residues, such as:

vsite_rcpt_residues=( 318 319 )

Maybe change `list_to_string()` to accept a single number in addition of a list and output something like '318 , ' in this case.
