### ISSUE TITLE
Bug: Config parser and single numbers

### ISSUE THREAD

**Issue by stefdoerr** [Gallicchio-Lab/AToM-OpenMM#75]
There is a quite sneaky bug with the config parser and single numbers. In the code in many places you assume that some variables in the config file hold list of integers. But if they don't it makes a mess.

The most obvious example which I found while debugging the app was here:
https://github.com/Gallicchio-Lab/AToM-OpenMM/blob/master/ommsystem.py#L413-L419

which if you specify in the cntl file:
```
LIGAND1_CM_ATOMS = 143
```

gives you the following:
```py
ipdb> cm_lig1_atoms
'143'
ipdb> lig1_atom_restr
[1, 4, 3]
```
which is obviously very wrong since it will restrain some random single-digit atoms instead of the ligand.

As per the tutorial here https://www.compmolbiophysbc.org/atom-openmm/atom-system-setup you can actually select a single atom in the ligand so it's not a weird use-case
> The centroid of the ligand could be defined in terms of all of the atoms of the ligand, but, especially for large ligands, it could make more sense to consider the centroid of only the core of the ligand, or even only one reference atom of the ligand. 

Practically in any place you assume a list is returned from the config parser there should be a check like this:
```py
#ligand 1 Vsite restraint
cm_lig1_atoms = self.keywords.get('LIGAND1_CM_ATOMS')   #indexes of ligand atoms for CM-CM Vsite restraint
if cm_lig1_atoms is not None:
    if isinstance(cm_lig1_atoms, str):
        cm_lig1_atoms = [cm_lig1_atoms]
    lig1_atom_restr = [int(i) for i in cm_lig1_atoms]
```
which converts it to a list before converting to integers

**Comment by egallicc** [comment]
It should be:
```
LIGAND1_CM_ATOMS = 143,
```

**Comment by stefdoerr** [comment]
Yes that would fix it as well. But do you trust your users (or yourself) enough to not forget to put a comma? I personally don't trust myself :laughing: There is no logging on which atoms the forces are applied to either, so you never notice it practically. In our case since the ligands are quite stable in the pocket and never left this would have the effect of pulling the N-terminal of the protein into the binding pocket but due to CA restraints would not be able to.
