### ISSUE TITLE
Aromatic ring explosions during equilibration

### ISSUE THREAD

**Issue by stefdoerr** [Gallicchio-Lab/AToM-OpenMM#76]
I've been experiencing explosions in my RBFE equilibrations with NaN coordinates on a tiny toy system I wrote which includes benzene and toluene. It's been parameterized with GAFF2. After a very close look I saw that the two molecules go through some very weird conformations eventually causing them to break and explode.
After zeroing the `ALIGN_K_PSI` parameter it seems to not happen anymore.

I am wondering if you have some intuition on why the forces would be so great as to break the planarity of aromatic rings. I've looked at the simulation and benzene never gets specially close to the peptide (closest I saw was 3.2A between two hydrogens). The tutorial also mentions that aromatic rings are good targets for alignment due to their rigidity.

![image](https://github.com/Gallicchio-Lab/AToM-OpenMM/assets/7935362/428cbf26-d369-45fa-ab0d-761343eabff7)
![image](https://github.com/Gallicchio-Lab/AToM-OpenMM/assets/7935362/9236ad56-4ae7-44db-b362-e3c88e61d66f)
![image](https://github.com/Gallicchio-Lab/AToM-OpenMM/assets/7935362/457c7bf5-141e-42be-9266-4349ba84cd90)

The alignment atoms I've chosen can be seen here colored based on their matching order.
![image](https://github.com/Gallicchio-Lab/AToM-OpenMM/assets/7935362/d1462d6e-ff6f-4a1f-9746-46022eeb2c7b)

**Comment by stefdoerr** [comment]
[toy_system.zip](https://github.com/Gallicchio-Lab/AToM-OpenMM/files/14512046/toy_system.zip)

Files for reproducing the crash. It crashes around half the times I run it, it's not very deterministic.
Since pocket positional restraints would not work, their coefficient is set to 0 and the ligands fly away but that's not the cause of the crash, sometimes it crashes on the first few steps of the simulation and I've also tried it with the positional pocket restraints I proposed in the other issue in which case they stay in place and it still crashes

**Comment by egallicc** [comment]
Does this occur if the alignment force constants are set to zero?

**Comment by stefdoerr** [comment]
It's an effect of ALIGN_K_PSI being set to 50.0 which we took from the Merck/Psivant dataset https://github.com/EricChen521/ATM_MerckSet/blob/main/targets/cdk8/free_energy/13~14/atom.cntl

I ran the equilibrations multiple times and only counted crashes which happened directly at the start of the equilibration. They often crash further on in the equilibration as well but I don't have the patience to run 60 full equilibrations today.

I tested with:
ALIGN_K_PSI = 50.0, ALIGN_K_PSI = 10.0 and ALIGN_K_PSI = 0.0

With constant 50 it directly crashed in 6/20 trials. With constant 10 and 0 it never crashed at the start. So I assume 50 is just too strong a constant and breaks the rings. I am not sure why it was chosen in the above dataset, but it seems to not be a good choice.

**Comment by stefdoerr** [comment]
I ran 3 full equilibrations with force constants 10, 25 and 50. Then I calculated all the dihedral angles of the aromatic rings of both toluene and benzene.
The histogram looks very similar between the three but once you look at the details you can see that 50 has many outliers
![image](https://github.com/Gallicchio-Lab/AToM-OpenMM/assets/7935362/6bf538d4-e11a-45fb-90b8-85e1d1ac547d)
zooming in on the region >0.5 angles
![image](https://github.com/Gallicchio-Lab/AToM-OpenMM/assets/7935362/addcf6c2-1ee6-4be5-813c-4beac8af386f)

The 50 force constant simulation has 68 conformers with dihedral angles on the aromatic ring larger than 0.7 radians. (in 10 and 25 they are all under 0.68). Same exact with toluene.
