### ISSUE TITLE
Proposal: Position-based restraints for the binding pocket

### ISSUE THREAD

**Issue by stefdoerr** [Gallicchio-Lab/AToM-OpenMM#77]
The current definition of the flat-bottomed potential for keeping the ligand inside the pocket, which is defined by the closest CA atoms to the bound ligand seems a bit risky to me. As the COM of those CA atoms could be quite far from the COM of the bound ligand and thus could pull the ligand closer to the receptor if the flat-bottom is not wide enough. It sort of assumes that the ligand is enveloped by the receptor but would probably not work too nice on flatter pockets.

Considering that we usually restrain the CA atoms of the receptor, the absolute coordinates of the pocket are not changing and thus we could use absolute XYZ coordinates to keep the ligand within a FB-potential defined from it's starting conformation.

I wrote such a restraint and am currently testing it and it seems to work pretty well. It's a simple modification of the existing restraint but it ignores the receptor COM coordinates and just uses fixed XYZ coordinates as the reference points.

```py
    def addVsiteRestraintForceCM(self,
                          lig_cm_particles = None, pos = None,
                          kfcm = 0.0 * kilocalorie_per_mole/angstrom**2,
                          tolcm = 0.0 * angstrom,
                          offset = [0., 0., 0.] * angstrom):
        """
        Adds a flat-bottom quadratic potential restraint to keep the the CM of the ligand atoms 
        near the CM of the receptor atoms. This potential is used to define the spatial extent of
        the binding site.

        Parameters
        ----------
        lig_cm_particles: list of ints
            List of the indexes of the atoms that define the CM of the ligand molecule
        pos : list of floats
            The absolute XYZ position to which to restrain the ligands
        kfcm : Quantity in energy/distance^2 units
            Force constant of the quadratic potential
        tolcm : Quantity in distance units
            Tolerance of the flat-bottom restraint
        offset : List of 3 Quantity's in distance units
            Center of the restraint. The potential is applied to the CM-CM distance after subtracting offset.
            It is used to keep the CM-CM distance near offset.

        Returns
        -------
        The CM-CM restraint Force object added to the OpenMM system

        """
        assert len(lig_cm_particles) > 0

        expr = "(kfcm/2)*step(d12-tolcm)*(d12-tolcm)^2 "
        expr += " ; d12 = sqrt((x1 - offx - posx)^2 + (y1 - offy - posy)^2 + (z1 - offz - posz)^2 ) ; "
        force = None
        if self.CMCMDistForce is None:
           self.CMCMDistForce  =  mm.CustomCentroidBondForce(2,expr)
           force = self.CMCMDistForce
           force.addPerBondParameter("kfcm")
           force.addPerBondParameter("tolcm")
           force.addPerBondParameter("offx")
           force.addPerBondParameter("offy")
           force.addPerBondParameter("offz")
           force.addPerBondParameter("posx")
           force.addPerBondParameter("posy")
           force.addPerBondParameter("posz")
           numgroups = 0
           self.system.addForce(force)
        else:
            force = self.CMCMDistForce
            numgroups = force.getNumGroups()
        force.addGroup(lig_cm_particles) #g1 CM of lig
        force.addGroup(lig_cm_particles) #add fake unused second group (can I remove this???)
        kfc = kfcm / (kilojoule_per_mole/nanometer**2)
        tolc = tolcm / nanometer
        offv = offset / nanometer
        groups = [numgroups + 0, numgroups + 1]
        params = [kfc, tolc, offv[0], offv[1], offv[2], pos[0], pos[1], pos[2]]
        print(f"Adding Vsite Restraint Force CM on ligand atoms {lig_cm_particles} with params {params}")
        force.addBond(groups, np.array(params, dtype=np.double))
        return force
```

**Comment by egallicc** [comment]
AToM-OpenMM does not set the binding site region based on the closest CA atoms. Setting the atoms that define the center of the binding site region is up to the user.

For "flat" binding sites we have sometimes used the LIGOFFSET parameter. Despite the name (it was introduced originally to do something else) it adds a displacement to the CM of the receptor.

In principle, defining the binding site in terms of lab coordinates makes the binding free energy dependent on them. It would be a particularly bad choice if the receptor is free to move.

**Comment by stefdoerr** [comment]
Isn't LIGOFFSET also lab coordinates though? I assume it's a xyz translation vector? Excluding a rigid translation of the protein if there is a rotation of it then the axes of the offset are wrong.

But I agree, the positional restraint should only be used if the receptor or restrained in space. Something like LIGOFFSET would work as well but it requires more manual user setup where they need to calculate what that offset is, while it's easy to automatically calculate the initial position of the bound ligand.

**Comment by egallicc** [comment]
> Isn't LIGOFFSET also lab coordinates though? 

Yes, and so is DISPLACEMENT. It's a defect of the implementation that we might address in the future. However, a lab coordinate dependence on a vector displacement is a lesser issue than a positional dependence.
 
> Something like LIGOFFSET would work as well, but it requires more manual user setup where they need to calculate what that offset is, while it's easy to automatically calculate the initial position of the bound ligand.

While we provide some setup workflow examples, system setup and automation is up to the user. Some corporate users have deployed their own setup workflows, while others have reimplemented ATM essentially from scratch. So you are more than welcome to develop, use, and distribute setup workflows and modified implementations. However, because it goes against the statistical mechanics theory of molecular binding, a binding site definition based on lab coordinates cannot be accepted in this repository.

**Comment by stefdoerr** [comment]
okay, thank you for the clarifications!
