### ISSUE TITLE
CDK2 results 

### ISSUE THREAD

**Issue by kexul** [Gallicchio-Lab/AToM-OpenMM#8]
Hi, I've followed the CDK2 example and finished the simulation with the default parameters. Here is the result I get: 

| mol0    | mol1 | AToM      | Schrodinger | Exp   | ΔΔG abs(exp-Schrodinger) | ΔΔG abs(exp-AToM) |
|---------|------|-----------|-------------|-------|--------------------------|-------------------|
| 1h1q    | 1h1s | -1.634153 | -2.72       | -3.07 | 0.35                     | 1.085847          |
| 1h1q    | 1oi9 | -2.542133 | -1.7        | -1.56 | 0.14                     | 0.842133          |
| 1h1q    | 1oiu | -2.200761 | -1.71       | -0.91 | 0.8                      | 0.490761          |
| 1h1q    | 1oiy | -2.963897 | -1.92       | -1.61 | 0.31                     | 1.043897          |
| 1h1r    | 1oiu | -1.174842 | -1.25       | -1.41 | 0.16                     | 0.075158          |
| 1oi9    | 1h1s | -3.588427 | -0.81       | -1.51 | 0.7                      | 2.778427          |
| 1oi9    | 1oiy | -1.220238 | 0.49        | -0.04 | 0.53                     | 1.710238          |
| 1h1q    | 1h1r | 1.025821  | 0.14        | 0.51  | 0.37                     | 0.885821          |
| Average |      |           |             |       | 0.42                     | 1.11403525        |

It seems like most of the pairs' ΔΔG are overestimated, are there parameters I can tune to reduce the error? 

Many thanks!

Result analyzed by [cinnabar](https://github.com/OpenFreeEnergy/cinnabar): 
Pairwise ΔΔG|Converted to ΔG
:-------------------------:|:-------------------------:
![2022年11月14日_cdk2_ddg](https://user-images.githubusercontent.com/5920217/201824957-aea91619-85e6-4dbb-b5a3-a6443af1d2e8.jpg) | ![2022年11月14日_cdk2_dg](https://user-images.githubusercontent.com/5920217/201824945-c1bc4236-ae66-47a2-9152-7d56f934df47.jpg)

**Comment by egallicc** [comment]
Thank you for sharing the CDK2 results. There are many factors that affect precision/accuracy. We will follow up soon to see if your results are consistent with ours.

**Comment by sheenam1509** [comment]
Hello, thank you for using AToM-OpenMM. I see most of your results are in a good ballpark except for ones having **1h1s** as the ligand in the RBFE PAIR. The torsion highlighted in the picture below seems to be stuck in the starting conformation of the ligand, leading to biased results in the Free Energy Calculations.


<img width="389" alt="Screen Shot 2022-11-17 at 11 58 14 AM" src="https://user-images.githubusercontent.com/76069815/202509833-c135b2fa-bb66-44ed-b377-ab5989172824.png">

In our lab, we use _metadynamics_ to target this _torsion_ as the collective variable (can be distance, angle, too) to sample the slow degrees of freedom. This way, all the ligand conformations are attained using the bias potential, leading to better Free energy estimates. 

Schrodinger particularly used FEP-REST for enhanced sampling of the ligand 1h1s. Please let me know if you may need more context on this, and I can provide you with the files and the protocol related to metadynamics for AToM-OpenMM.

Hope this helped, thank you.

**Comment by kexul** [comment]
Thanks for your reply! @egallicc @sheenam1509 It's a pleasure to try this new method. The system could be set up quite easily using the script you provided, I'll try my own ligands and proteins soon. 😃 

>  In our lab, we use metadynamics to target this torsion as the collective variable (can be distance, angle, too) to sample the slow degrees of freedom.

Wow, that's a field I've never touched, many thanks for your suggestion! 🤗 
Before that, may I ask how to determine the **slow degree of freedom**? Are there some qualitative or quantitative indicators to measure that? 
Actually, I've done the same perturbations using [somd-freenrg](https://github.com/michellab/Sire) (no enhanced sampling method used). Taking `1oi9->1h1s` as an example, I get `-1.1, -0.5, -1.28` in three runs, which seems to be very close to the exp value `-1.51`. I'm not sure whether the values are obtained by accident or there is no need for enhanced sampling.

**Comment by kexul** [comment]
Update: I just finished another two runs. Here is the full result: 
| mol0 | mol1 | run1  | run2  | run3  |
|------|------|-------|-------|-------|
| 1h1q | 1h1s | -1.63 | -0.79 | -1.83 |
| 1h1q | 1oi9 | -2.54 | -1.54 | -2.29 |
| 1h1q | 1oiu | -2.20 | -2.53 | -2.41 |
| 1h1q | 1oiy | -2.96 | -1.34 | -0.9  |
| 1h1r | 1oiu | -1.17 | -3.16 | -3.6  |
| 1oi9 | 1h1s | -3.59 | -0.08 | 1.11  |
| 1oi9 | 1oiy | -1.22 | 1.13  | 0.88  |
| 1h1q | 1h1r | 1.03  | -1.89 | -1.68 |

**Comment by egallicc** [comment]
Hi. Right, yours is more of a research question than a software question. As you know, there are many factors to consider to obtain reliable predictions of the binding free energies of macromolecular complexes. The issue of conformational sampling that you mentioned is definitively a big one. People (including my lab) use a variety of tricks to speed up the sampling of slow degrees of freedom. If I am not mistaken, this benchmark set was prepared to probe this question.

Protein and ligand preparation, setting correct protonation and tautomerization states, and other "chemical" aspects are also very important. And predictions might be inaccurate even with the best effort. Issues such as force field quality, receptor reorganization, and changes in hydration and the binding poses, to name a few, are, for the most part, unknowables that can have a large influence on the predictions.

Protein-ligand binding free energy prediction is very hard. A binding free energy software like AToM/OpenMM is only the starting point.

**Comment by egallicc** [comment]
No. REST would be very nice, but it requires modifications of OpenMM's energy core routines and would limit the choice of the energy model. The primary objective of our efforts is straightforward implementations of free energy models applicable with any energy function. We are not ready to give that up.

We will be coming up soon with a metadynamics-based alternative.
