### ISSUE TITLE
Confused about lenght of run

### ISSUE THREAD

**Issue by GattiMh** [Gallicchio-Lab/AToM-OpenMM#83]
Hello,

thanks for uploading the code.
I have been running some tests on the example presented as well as my own one.
I have set up a run with:

PRODUCTION_STEPS = '10'
PRNT_FREQUENCY = '10'
TRJ_FREQUENCY = '10'
HMASS=1.5
TIMESTEP=0.04

I was expecting to finish in few minutes but instead it seems to go on for hours.
I've selected such ranges just to test the script ./run.sh.

Clearly, I'm missing some other parameter in the configuration file?

Many thanks

**Comment by egallicc** [comment]
The runtime is controlled by WALL_TIME and MAX_SAMPLES.

The MD time-step is usually 0.002 ps; or 0.004 ps if the system is prepared with hydrogen mass repartitioning. 0.04 ps is too large.

HMASS is ignored in the latest released version. The system definition, including atomic masses, is taken from the `_sys.xml` file prepared with the `make_atm_from_rcpt_lig.py` utility or similar.
