### ISSUE TITLE
Gibbs or Helmholtz free energy in final result? 

### ISSUE THREAD

**Issue by smutao** [Gallicchio-Lab/AToM-OpenMM#88]
It seems that NPT ensemble is only used in the `structprep` section, and the production AToM MD simulation is all conducted in the NVT ensemble (fixed volume). 

Therefore, should the ΔΔG (**Gibbs** free energy change) reported by the R script be changed into ΔΔA (**Helmholtz**)? 

Please correct me if I'm wrong. Thank you.

**Comment by egallicc** [comment]
Yes, strictly speaking, and as currently implemented, AToM is limited to the NVT canonical ensemble and produces Helmholtz binding free energies. I agree that it would be more correct to use the letter `A`.

**Comment by smutao** [comment]
Thank you very much for the clarification.
