### ISSUE TITLE
Choice of reference atoms

### ISSUE THREAD

**Issue by egallicc** [Gallicchio-Lab/AToM-OpenMM#89]
@egallicc Hi, I was also wondering a bit about the selection of the three alignment atoms between the two ligands. What is the ideal selection and how does it affect the RBFE calculations? If you have two large flexible ligands would it be good enough to align them on three atoms of a single, stable, aromatic ring in the core and leave the rest to rotate freely?

From the paper I find these quotes:

> Here we also introduce a restraining potential that maintains ligand alignment in order to enhance the convergence of the calculations for similar ligand pairs and we show mathematically that these calculations yield unbiased binding free energy estimates.

> For ligands with similar shape, the occurrences of severe clashes with nearby atoms would be considerably reduced if the two ligands land in a similar location and orientation when their positions are swapped.  In order to improve convergence, we therefore introduce restraint potentials that help to maintain the positions and orientations of the two ligands in approximate alignment. 

This would indicate that choosing a single ring in a large ligand would slow down convergence significantly due to clashes. Although later on you mention:

> This suggests that allowing for more flexibility can lower the free energy of the intermediate state in which the two ligands simultaneously occupy the binding cavity and thus facilitate convergence.

So maybe the flexibility would be beneficial after all for larger ligands?

If the ligands are significantly different, aligning on three atoms distributed all over the ligand (let's say two atoms on the total extremes of the molecule and one atom in the COM), even if they are initially very close to their matching atoms, could keep the ligands from interacting correctly with the binding site.

So I'm rather tending in favour of choosing three atoms in a common stable ring in the two ligands

_Originally posted by @stefdoerr in https://github.com/Gallicchio-Lab/AToM-OpenMM/issues/5#issuecomment-2217188204_
            
Hello. A bit about choosing reference atoms is discussed [here](https://www.compmolbiophysbc.org/atom-openmm/atom-system-setup#h.vndnoxipr7qs).

Using three atoms within a rigid ring near the center of a ligand is generally a good strategy. However, as you mentioned, alignment restraints will not affect the flexibility of a large ligand far away from the ring. Dual-topology alchemical approaches such as ATM are not optimal for RBFEs between pairs of large ligands because, unlike single-topology, all of the atoms of the two ligands move independently, even those in the common region.

At the alchemical intermediate, the two ligands tend to align on their own to fit the receptor binding site. Suboptimal alignment restraints that force them to align in some other way will increase the free energy of the alchemical intermediate, likely slowing down convergence. In the case discussed in the paper, relaxing the restraints was found to be beneficial.

The alignment restraints act only on the external degrees of the freedom of the ligands. They have no effect on the ligand-receptor interactions at the physical end states. Alignment restraints are only a device to speed up convergence. They have no effect on the accuracy of the model.

The three pair of atoms used in the alignment restraints are meant to correspond to the position, orientation, and rotation of the molecule. Alignment restraints based on atoms in flexible portions of the ligands also reflect internal degrees of freedom and are not as effective, in my opinion. So, yes, I tend to agree with your conclusion.

**Comment by stefdoerr** [comment]
Thanks! That was a very useful resource
