### ISSUE TITLE
determine lambda

### ISSUE THREAD

**Issue by researchhh** [Gallicchio-Lab/AToM-OpenMM#9]
Hi,

Good afternoon! I successfully performed the simulations test cases and did the analysis. I am trying to set up the systems for my own protein for relative binding free energy calculations. I noticed that the lambdas (e.g., lambdas, lambda1, and lambda2) are different for the temoa-g1-g4 and CDK systems in the test cases. Based on your experience, is there any difference in the result if we use different lambdas? Is there any good way to determine the lambdas for other systems?

Many thanks!!!

**Comment by egallicc** [comment]
I wish there was! 

In principle, any alchemical pathway yields the same free energy difference. In practice, optimization of the alchemical potential and the lambda schedule is often necessary to achieve convergence in a reasonable simulation time. 

The design of alchemical pathways is an intensively studied problem. It is also a classical chicken and egg situation. An equilibrated alchemical ensemble holds the data needed to determine the best alchemical pathway. However, often some optimization of the alchemical potential and schedule is required to achieve equilibration. 

These are two recent works of ours on the topic:
[Pal et al, 2019](https://aip.scitation.org/doi/10.1063/1.5123154)
[Khuttan et al, 2021](https://aip.scitation.org/doi/10.1063/5.0036944)

In these studies, we found that the softplus alchemical potential used in AToM is particularly good at overcoming bottlenecks. We also identified a graphical procedure to optimize the lambda schedule.

The lambda schedule used in the CDK2 example is a good optimized general-purpose choice in our experience. The temoa example uses a traditional linear alchemical potential.

**Comment by researchhh** [comment]
Thank you for the reply! It is really helpful!

I have one more question:

I saw that the script is using Monte Carlo Barostat. In my case, I would like to use the AToM for my membrane systems. Do you think it is still feasible? Or do I need to use MonteCarloMembrane Barostat in OpenMM? (Any suggestion would be very helpful!)

Thanks a lot!!

**Comment by egallicc** [comment]
Sorry, we do not have much experience with RBFE calculations for membrane-bound receptors. In general, any setup recommended for straight MD calculations is applicable with AToM-OpenMM.

**Comment by researchhh** [comment]
Thank you very much! I will try it!
