### ISSUE TITLE
Positive ABFE result 

### ISSUE THREAD

**Issue by nonsensejoke** [Gallicchio-Lab/AToM-OpenMM#90]
Hello Professor Gallicchio,

I tried to run ABFE simulation with AToM for a protein+ligand system built with my own tool chain.
I first obtained AMBER prm7/rst7 files, then convert them into xml/pdb files for OpenMM.  

I tried several ligands against the same receptor protein and found that **all** my ABFE results are positive (I expect negative values as the ABFE examples). 
I wonder what the cause can be in this situation. 

In the zip file below, I have attached the `cntl` file, `uwham_analysis` input/output, the `analyze.sh` script and Rplots.pdf. 
[atom-abfe-result.zip](https://github.com/user-attachments/files/16263232/atom-abfe-result.zip)

Thank you for your time.

**Comment by egallicc** [comment]
The ligand is probably too large (56 atoms) for ABFE. The perturbation energy distributions (see Rplots.pdf) are disconnected. I recommend binding a fragment of the ligand first and then use RBFE to progressively build the full ligand. See https://pubs.rsc.org/en/content/articlelanding/2023/cp/d3cp02125d for an example.

I also recommend double-checking the location of the binding site region (the LIGAND_CM_ATOMS, RCPT_CM_ATOMS, CM_KF, and CM_TOL settings) to confirm that it is consistent with the desired binding pose.

**Comment by nonsensejoke** [comment]
Thank you very much for your suggestion and the paper. I will look into this.
