### ISSUE TITLE
Compatibility with CustomNonBonded Forces from *.xml file

### ISSUE THREAD

**Issue by hongsrich** [Gallicchio-Lab/AToM-OpenMM#91]
Hi,

I was wondering if it would be possible to have the option to load in CustomNonBonded forces here ( I have a *.xml with a Custom Non Bonded force and seems like the loop is exiting right after it reads in the NonBonded Forces).  After when I am running MD,  the "CustomNonBonded" force group is not being read from the xml file and results in the simulation crashing.  I was able to get around the issue by changing parts of the set up to recognize the CustomNonBonded forces from the *.xml file, but am not sure where else I will need to change this.  

See below for the part of the code in the simulation set up I am referring to.  

![image](https://github.com/user-attachments/assets/ac46b3e1-b275-4cae-9aa3-ff9abd9fa760)

Thanks a lot !

**Comment by egallicc** [comment]
That is indeed the code section that selected the Forces to place under the control of ATMForce. Find similar sections in ommsystem.py and change them in the same way.
