### ISSUE TITLE
Change ligand position restraint

### ISSUE THREAD

**Issue by syxchen** [Gallicchio-Lab/AToM-OpenMM#93]
Hi! I was wondering if it was possible to only impose partial restraints on the ligands in RBFE calculations? i.e. only put restraint on the center atom of the two ligands (first reference atom) but remove restraints on the orientation and rotation restraints (second and third reference atoms). I tried to include only the first ligand reference atom in the input set-setting.sh but the program terminates with an error. Any help would be greatly appreciated!

**Comment by egallicc** [comment]
Yes, this is supported. While all three reference atoms must be indicated, the the orientational alignment restraints can be turned off by setting to zero the corresponding force constants (ALIGN_KF_THETA and/or ALIGN_KF_ PSI). When, for example, ALIGN_KF_ PSI is set to zero the indexes of the third reference atoms are arbitrary. 

Note that there is an implied hierarchy in the alignment restraints. It probably does not make sense to turn off the pitch angle restraint (theta) without also turning off the roll angle restraint (psi).
