### ISSUE TITLE
Question: parallelisation of replica exchange on CPU

### ISSUE THREAD

**Issue by FlorisLoffler** [Gallicchio-Lab/AToM-OpenMM#96]
While going through the examples, I was trying to let the rbfe_explicit.py and abfe_explicit.py programs run parallel on a cluster of 16 CPUs. However, this does not seem possible, and I was wondering if AToM-OpenMM can run parallel replica exchange on CPUs, or if parallelization is only possible for GPUs.

While trying to use CPUs, I changed the nodefile to localhost,0:0,16,CPU,,/tmp and set OPENMM_PLATFORM = CPU. Although I use a batch file with slurm commands including

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16

it seems that the simulation is not running parallel.  I tried various combinations of different tasks-per-node and cpus-per-task values, but nothing seemed to work. After 4 hours of simulation, only 10 replicas have been launched, (with non going to a further cycle), while the examples show that 4 hours of simulation with GPUs yielded 38 samples, quite a difference.
So, is parallelization for CPUs implemented in AToM?

**Comment by egallicc** [comment]
I cannot reproduce the problem you are describing. I'm getting about 11 ns/day on an 8-core i7 Intel processor for the temoa-g1 example. The worker uses the 8 cores as expected based on `top`.

Could you please share an example?

However, the `structprep` scripts do not appear to support the CPU platform correctly. It will be fixed soon.

**Comment by FlorisLoffler** [comment]
Thank you egallicc for your response,

For the temoa-g1-g4 example, the structprep speed differed a lot, ranging from 0.68 ns/day for equilibration at lambda = 1/2  to  1.25 ns/day for NPT and NVT equilibration (in total taking 22 hours). For the rbfe_explicit.py simulation, the  temoa-g1-g4_stat.txt file yields 
Replica  State  Lambda Lambda1 Lambda2 Alpha Uh W0coeff Temperature Status  Cycle 
     0       0   0.000  0.000  0.000  0.000   0.00   0.00 300.00     W      2
     1       2   0.100  0.100  0.100  0.000   0.00   0.00 300.00     W      2
     2       1   0.050  0.050  0.050  0.000   0.00   0.00 300.00     W      2
     3       3   0.150  0.150  0.150  0.000   0.00   0.00 300.00     W      2
     4       5   0.250  0.250  0.250  0.000   0.00   0.00 300.00     W      2
     5       4   0.200  0.200  0.200  0.000   0.00   0.00 300.00     W      2
     6       6   0.300  0.300  0.300  0.000   0.00   0.00 300.00     W      2
     7       7   0.350  0.350  0.350  0.000   0.00   0.00 300.00     W      2
     8       8   0.400  0.400  0.400  0.000   0.00   0.00 300.00     R      1
     9       9   0.450  0.450  0.450  0.000   0.00   0.00 300.00     W      1
    10      10   0.500  0.500  0.500  0.000   0.00   0.00 300.00     W      1
    11      11   0.500  0.500  0.500  0.000   0.00   0.00 300.00     W      1
    12      12   0.550  0.450  0.450  0.000   0.00   0.00 300.00     W      1
    13      13   0.600  0.400  0.400  0.000   0.00   0.00 300.00     W      1
    14      14   0.650  0.350  0.350  0.000   0.00   0.00 300.00     W      1
    15      15   0.700  0.300  0.300  0.000   0.00   0.00 300.00     W      1
    16      16   0.750  0.250  0.250  0.000   0.00   0.00 300.00     W      1
    17      17   0.800  0.200  0.200  0.000   0.00   0.00 300.00     W      1
    18      18   0.850  0.150  0.150  0.000   0.00   0.00 300.00     W      1
    19      19   0.900  0.100  0.100  0.000   0.00   0.00 300.00     W      1
    20      20   0.950  0.050  0.050  0.000   0.00   0.00 300.00     W      1
    21      21   1.000  0.000  0.000  0.000   0.00   0.00 300.00     W      1
Running = 1
Waiting = 21

after 4 hours. I would expect that if my simulation was parallel, I would see multiple replicas running at the same time, right?
Furthermore, the temoa-g1-g4.log file yields

#"Step","Temperature (K)","Speed (ns/day)"
860000,297.5813333947177,0
880000,298.87405966736867,2.03
900000,300.63178681169904,2.03
920000,296.33614233315905,2.03
940000,298.69614641861466,2.03
960000,300.7702824765069,2.03
980000,297.73661692970103,2.03
1000000,301.3534165848789,2.02
1020000,298.63991547757513,2.02

So a speed of about 2.0 ns/day. 
The simulation also doesn't seem to have created .dcd files (for trajectories), as the various r0 r1 r2 etc. directories only have XML, out and xtc files.

Maybe there are more settings I should change for CPU parallelization?

**Comment by egallicc** [comment]
The structprep scripts do not appear to set the CPU platform correctly. They will be fixed shortly.

Add additional devices (each on his own line) to the nodefile to run multiple replicas in parallel. Specifying a CPU device with multiple threads increases the level of parallelization of the calculation of the energy function for one replica.

AToM saves trajectory files in xtc format. Does the documentation say dcd somewhere?

**Comment by FlorisLoffler** [comment]
Thank you, I will try to add additional devices to the nodefile. It seems to be working.

The AToM Simulation and Analysis section https://www.compmolbiophysbc.org/atom-openmm/atom-simulation says that "AToM production generates directories r0, r1/, r2/, etc., that contain .dcd MD coordinate trajectories, ". Furthermore, the examples state that "These folders contain (...) a .dcd trajectory file ".

**Comment by egallicc** [comment]
The structprep scripts now support the CPU platform. The number of cores is obtained from the `OMP_NUM_THREADS` environment variable.

The documentation has been updated. Thank you.

**Comment by FlorisLoffler** [comment]
Thank you for the swift changes. I am running Structprep again, which now seems to be faster.

**Comment by FlorisLoffler** [comment]
Problems have been solved.

**Comment by FlorisLoffler** [comment]
When constructing a nodefile for parallel CPU RE simulations, should all of the cores receive their own line _and_ a specification of the amount of threads?

For instance, if I were to run 16 cores, a nodefile could look like this:
localhost,0:0,16,CPU,,/tmp
localhost,0:0,16,CPU,,/tmp
localhost,0:0,16,CPU,,/tmp
localhost,0:0,16,CPU,,/tmp
localhost,0:0,16,CPU,,/tmp
localhost,0:0,16,CPU,,/tmp
localhost,0:0,16,CPU,,/tmp
localhost,0:0,16,CPU,,/tmp
localhost,0:0,16,CPU,,/tmp
localhost,0:0,16,CPU,,/tmp
localhost,0:0,16,CPU,,/tmp
localhost,0:0,16,CPU,,/tmp
localhost,0:0,16,CPU,,/tmp
localhost,0:0,16,CPU,,/tmp
localhost,0:0,16,CPU,,/tmp

And for 32 cores, a nodile would look like this
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp
localhost,0:0,32,CPU,,/tmp

Is this right, or should the nodefile look different?

Furthermore, when I put more than 15 devices into the nodefile, the simulation returns an out of boudns error. It seems that one of the replicas is still running on a reference, but I never specified that. Is this supposed to be the case?

And lastly, per verification, OMP_NUM_THREADS only has to be specified for the preparation, and not for the RE, right?

**Comment by egallicc** [comment]
If, for example, you have 16-core system, this nodefile:
```
localhost,0:0,16,CPU,,/tmp
```
would run one replica on all 16 cores. If on the other hand the nodefile says:
```
localhost,0:0,8,CPU,,/tmp
localhost,0:1,8,CPU,,/tmp
```
AToM would run two replicas concurrently using 8 cores each.

The nodefile:
```
localhost,0:0,16,CPU,,/tmp
localhost,0:1,16,CPU,,/tmp
```
would run two replicas with 16 cores each. I guess it would probably work but it would be inefficient in this example because each core would be overloaded.

The format for each line of the nodefile is
```
<hostname>,<platform_index>:<device_index>,<num_cores>,<architecture_name>,<username>,<tempfolder> 
```
The last two items, `<username>` and `<tempfolder>` are not currently used. `<device_index>` is probably not relevant for the CPU platform.

**Comment by egallicc** [comment]
And, yes, OMP_NUM_THREADS is a setting specific for the structprep applications. The production step gets the computational devices from the nodefile.

**Comment by FlorisLoffler** [comment]
Thank you for your response.
